In [2]:
from pathlib import Path
from mth5.mth5 import MTH5

from mth5 import read_file

In [4]:
with MTH5() as m:
    m = m.open_mth5(r"c:\Users\jpeacock\OneDrive - DOI\MTData\CM2025\mth5\cm205.h5", mode="a")
    hy = m.get_channel("cm205", "sr256_0001", "hy", "cm2025").to_channel_ts()
    run_group = m.get_run("cm205", "sr256_0002", "cm2025")
    hy_slice = hy.get_slice(run_group.metadata.time_period.start, end=run_group.metadata.time_period.end)
    run_group.from_channel_ts(hy_slice)
    m.remove_run("cm205", "sr256_0001", "cm2025")
    print(run_group)

2026-01-28T10:42:11.373278-0800 | INFO | mth5.groups.base | _remove_group | line: 729 | Deleting a station does not reduce the HDF5file size it simply remove the reference. If file size reduction is your goal, simply copy what you want into another file.
/Experiment/Surveys/cm2025/Stations/cm205/sr256_0002:
====================
    --> Dataset: ex
    .................
    --> Dataset: ey
    .................
    --> Dataset: hx
    .................
    --> Dataset: hy
    .................
    --> Dataset: hz
    .................
2026-01-28T10:42:12.259288-0800 | INFO | mth5.mth5 | close_mth5 | line: 899 | Flushing and closing c:\Users\jpeacock\OneDrive - DOI\MTData\CM2025\mth5\cm205.h5

In [5]:
with MTH5() as m:
    m = m.open_mth5(r"c:\Users\jpeacock\OneDrive - DOI\MTData\CM2025\mth5\cm205.h5", mode="a")
    rs = m.run_summary

2026-01-28T10:42:34.122672-0800 | INFO | mth5.mth5 | close_mth5 | line: 899 | Flushing and closing c:\Users\jpeacock\OneDrive - DOI\MTData\CM2025\mth5\cm205.h5

In [6]:
rs

,channel_scale_factors,duration,end,has_data,input_channels,mth5_path,n_samples,output_channels,run,sample_rate,start,station,survey,run_hdf5_reference,station_hdf5_reference
0,"{'ex': 1.0, 'ey': 1.0, 'hx': 1.0, 'hy': 1.0, '...",69884.000000,2025-06-07 18:34:42+00:00,True,"[hx, hy]",c:/Users/jpeacock/OneDrive - DOI/MTData/CM2025...,69885,"[ex, ey, hz]",sr1_0001,1.0,2025-06-06 23:09:58+00:00,cm205,cm2025,<HDF5 object reference>,<HDF5 object reference>
1,"{'ex': 1.0, 'ey': 1.0, 'hx': 1.0, 'hy': 1.0, '...",26083.968750,2025-06-07 06:59:41.968750+00:00,True,"[hx, hy]",c:/Users/jpeacock/OneDrive - DOI/MTData/CM2025...,6677497,"[ex, ey, hz]",sr256_0002,256.0,2025-06-06 23:44:58+00:00,cm205,cm2025,<HDF5 object reference>,<HDF5 object reference>
4,"{'ex': 1.0, 'ey': 1.0, 'hx': 1.0, 'hy': 1.0, '...",583.998047,2025-06-07 07:09:41.998047+00:00,True,"[hx, hy]",c:/Users/jpeacock/OneDrive - DOI/MTData/CM2025...,2392057,"[ex, ey, hz]",sr4096_0003,4096.0,2025-06-07 06:59:58+00:00,cm205,cm2025,<HDF5 object reference>,<HDF5 object reference>
2,"{'ex': 1.0, 'ey': 1.0, 'hx': 1.0, 'hy': 1.0, '...",28183.968750,2025-06-07 14:59:41.968750+00:00,True,"[hx, hy]",c:/Users/jpeacock/OneDrive - DOI/MTData/CM2025...,7215097,"[ex, ey, hz]",sr256_0004,256.0,2025-06-07 07:09:58+00:00,cm205,cm2025,<HDF5 object reference>,<HDF5 object reference>
5,"{'ex': 1.0, 'ey': 1.0, 'hx': 1.0, 'hy': 1.0, '...",583.994141,2025-06-07 15:09:41.994141+00:00,True,"[hx, hy]",c:/Users/jpeacock/OneDrive - DOI/MTData/CM2025...,2392057,"[ex, ey, hz]",sr4096_0005,4096.0,2025-06-07 14:59:58+00:00,cm205,cm2025,<HDF5 object reference>,<HDF5 object reference>
3,"{'ex': 1.0, 'ey': 1.0, 'hx': 1.0, 'hy': 1.0, '...",12284.000000,2025-06-07 18:34:42+00:00,True,"[hx, hy]",c:/Users/jpeacock/OneDrive - DOI/MTData/CM2025...,3144705,"[ex, ey, hz]",sr256_0006,256.0,2025-06-07 15:09:58+00:00,cm205,cm2025,<HDF5 object reference>,<HDF5 object reference>

In [7]:
new_hy = read_file(r"c:\Users\jpeacock\OneDrive - DOI\MTData\CM2025\cm219\cm219_20250605_194017_256_HY.Z3D")

2026-01-28T10:47:47.988586-0800 | WARNING | mth5.io.zen.zen | validate_gps_time | line: 1419 | Data block 3254 has a time difference between GPS stamps > 1 second [1.0029296875 s]
2026-01-28T10:47:47.989420-0800 | WARNING | mth5.io.zen.zen | validate_time_blocks | line: 1459 | Data block 3254 has 257 samples, expected 256.0 samples.

In [9]:
with MTH5() as m:
    m = m.open_mth5(r"c:\Users\jpeacock\OneDrive - DOI\MTData\CM2025\mth5\cm230.h5", mode="a")
    run_group = m.get_run("cm230", "sr256_0001", "cm2025")
    new_hy_slice = new_hy.get_slice(run_group.metadata.time_period.start, end=run_group.metadata.time_period.end)
    run_group.from_channel_ts(new_hy_slice)
    print(run_group)
    m.remove_run("cm230", "sr256_0002", "cm2025")

/Experiment/Surveys/cm2025/Stations/cm230/sr256_0001:
====================
    --> Dataset: ex
    .................
    --> Dataset: ey
    .................
    --> Dataset: hx
    .................
    --> Dataset: hy
    .................
    --> Dataset: hz
    .................
2026-01-28T10:49:03.089213-0800 | INFO | mth5.groups.base | _remove_group | line: 729 | Deleting a station does not reduce the HDF5file size it simply remove the reference. If file size reduction is your goal, simply copy what you want into another file.
2026-01-28T10:49:06.507081-0800 | INFO | mth5.mth5 | close_mth5 | line: 899 | Flushing and closing c:\Users\jpeacock\OneDrive - DOI\MTData\CM2025\mth5\cm230.h5

In [10]:
with MTH5() as m:
    m = m.open_mth5(r"c:\Users\jpeacock\OneDrive - DOI\MTData\CM2025\mth5\cm230.h5", mode="a")
    rs = m.run_summary

2026-01-28T10:49:21.963843-0800 | INFO | mth5.mth5 | close_mth5 | line: 899 | Flushing and closing c:\Users\jpeacock\OneDrive - DOI\MTData\CM2025\mth5\cm230.h5

In [11]:
rs

,channel_scale_factors,duration,end,has_data,input_channels,mth5_path,n_samples,output_channels,run,sample_rate,start,station,survey,run_hdf5_reference,station_hdf5_reference
0,"{'ex': 1.0, 'ey': 1.0, 'hx': 1.0, 'hy': 1.0, '...",70783.000000,2025-06-06 16:14:41+00:00,True,"[hx, hy]",c:/Users/jpeacock/OneDrive - DOI/MTData/CM2025...,70784,"[ex, ey, hz]",sr1_0001,1.0,2025-06-05 20:34:58+00:00,cm230,cm2025,<HDF5 object reference>,<HDF5 object reference>
1,"{'ex': 1.0, 'ey': 1.0, 'hx': 1.0, 'hy': 1.0, '...",8683.968750,2025-06-05 22:59:41.968750+00:00,True,"[hx, hy]",c:/Users/jpeacock/OneDrive - DOI/MTData/CM2025...,2223097,"[ex, ey, hz]",sr256_0001,256.0,2025-06-05 20:34:58+00:00,cm230,cm2025,<HDF5 object reference>,<HDF5 object reference>
5,"{'ex': 1.0, 'ey': 1.0, 'hx': 1.0, 'hy': 1.0, '...",583.996094,2025-06-05 23:09:41.996094+00:00,True,"[hx, hy]",c:/Users/jpeacock/OneDrive - DOI/MTData/CM2025...,2392057,"[ex, ey, hz]",sr4096_0003,4096.0,2025-06-05 22:59:58+00:00,cm230,cm2025,<HDF5 object reference>,<HDF5 object reference>
2,"{'ex': 1.0, 'ey': 1.0, 'hx': 1.0, 'hy': 1.0, '...",28183.968750,2025-06-06 06:59:41.968750+00:00,True,"[hx, hy]",c:/Users/jpeacock/OneDrive - DOI/MTData/CM2025...,7215097,"[ex, ey, hz]",sr256_0004,256.0,2025-06-05 23:09:58+00:00,cm230,cm2025,<HDF5 object reference>,<HDF5 object reference>
6,"{'ex': 1.0, 'ey': 1.0, 'hx': 1.0, 'hy': 1.0, '...",583.996094,2025-06-06 07:09:41.996094+00:00,True,"[hx, hy]",c:/Users/jpeacock/OneDrive - DOI/MTData/CM2025...,2392057,"[ex, ey, hz]",sr4096_0005,4096.0,2025-06-06 06:59:58+00:00,cm230,cm2025,<HDF5 object reference>,<HDF5 object reference>
3,"{'ex': 1.0, 'ey': 1.0, 'hx': 1.0, 'hy': 1.0, '...",28183.968750,2025-06-06 14:59:41.968750+00:00,True,"[hx, hy]",c:/Users/jpeacock/OneDrive - DOI/MTData/CM2025...,7215097,"[ex, ey, hz]",sr256_0006,256.0,2025-06-06 07:09:58+00:00,cm230,cm2025,<HDF5 object reference>,<HDF5 object reference>
7,"{'ex': 1.0, 'ey': 1.0, 'hx': 1.0, 'hy': 1.0, '...",583.998047,2025-06-06 15:09:41.998047+00:00,True,"[hx, hy]",c:/Users/jpeacock/OneDrive - DOI/MTData/CM2025...,2392057,"[ex, ey, hz]",sr4096_0007,4096.0,2025-06-06 14:59:58+00:00,cm230,cm2025,<HDF5 object reference>,<HDF5 object reference>
4,"{'ex': 1.0, 'ey': 1.0, 'hx': 1.0, 'hy': 1.0, '...",1183.996094,2025-06-06 15:29:41.996094+00:00,True,"[hx, hy]",c:/Users/jpeacock/OneDrive - DOI/MTData/CM2025...,994304,"[ex, ey, hz]",sr256_0008,256.0,2025-06-06 15:09:58+00:00,cm230,cm2025,<HDF5 object reference>,<HDF5 object reference>

In [11]:
with MTH5() as m:
    m = m.open_mth5(r"c:\Users\jpeacock\OneDrive - DOI\MTData\CM2025\mth5\cm230.h5", mode="a")
    m.remove_run("cm230", "sr1_0001", "cm2025")

    m.channel_summary.summarize()

    rs = m.run_summary
    run_list = []
    for row in rs.sort_values("start").itertuples():
        if row.has_data:
            run_list.append(m.from_reference(row.run_hdf5_reference).to_runts())
    
    combined_run = run_list[0].merge(run_list[1:], new_sample_rate=1)
    combined_run.run_metadata.id = "sr1_0001"
    
    combined_run_group = m.add_run("cm230", "sr1_0001", survey="cm2025")
    combined_run_group.from_runts(combined_run)
    combined_run_group.update_metadata()

2026-01-29T14:03:01.162611-0800 | INFO | mth5.groups.base | _remove_group | line: 729 | Deleting a station does not reduce the HDF5file size it simply remove the reference. If file size reduction is your goal, simply copy what you want into another file.
2026-01-29T14:03:14.062297-0800 | INFO | mth5.timeseries.run_ts | _align_channels | line: 584 | Channels do not have a common end, using latest: 2025-06-05T23:09:41.998047000
2026-01-29T14:03:30.008715-0800 | INFO | mth5.timeseries.run_ts | _align_channels | line: 584 | Channels do not have a common end, using latest: 2025-06-06T07:09:41.998047000
2026-01-29T14:03:40.453355-0800 | INFO | mth5.timeseries.run_ts | _align_channels | line: 584 | Channels do not have a common end, using latest: 2025-06-06T14:59:41.968750000
2026-01-29T14:03:48.447544-0800 | INFO | mth5.timeseries.run_ts | _align_channels | line: 584 | Channels do not have a common end, using latest: 2025-06-06T15:09:41.998047000
2026-01-29T14:03:53.866155-0800 | INFO | mth5.timeseries.run_ts | _align_channels | line: 584 | Channels do not have a common end, using latest: 2025-06-06T16:14:41.996094000
2026-01-29T14:03:54.925780-0800 | WARNING | mth5.timeseries.run_ts | validate_metadata | line: 1065 | end time of dataset 2025-06-05T22:59:41+00:00 does not match metadata end 2025-06-05T22:59:41.968750+00:00 updating metatdata value to 2025-06-05T22:59:41+00:00
2026-01-29T14:03:55.313933-0800 | WARNING | mth5.timeseries.scipy_filters | resample_poly | line: 699 | New sample rate is not an even number of original sample rate. The ratio is 4095.9999991232844.  Use the new dimensions with caution.
2026-01-29T14:03:55.381908-0800 | WARNING | mth5.timeseries.run_ts | validate_metadata | line: 1065 | end time of dataset 2025-06-05T23:09:41+00:00 does not match metadata end 2025-06-05T23:09:41.998047+00:00 updating metatdata value to 2025-06-05T23:09:41+00:00
2026-01-29T14:03:56.444243-0800 | WARNING | mth5.timeseries.run_ts | validate_metadata | line: 1065 | end time of dataset 2025-06-06T06:59:41+00:00 does not match metadata end 2025-06-06T06:59:41.968750+00:00 updating metatdata value to 2025-06-06T06:59:41+00:00
2026-01-29T14:03:56.834827-0800 | WARNING | mth5.timeseries.scipy_filters | resample_poly | line: 699 | New sample rate is not an even number of original sample rate. The ratio is 4095.9999991232844.  Use the new dimensions with caution.
2026-01-29T14:03:56.903142-0800 | WARNING | mth5.timeseries.run_ts | validate_metadata | line: 1065 | end time of dataset 2025-06-06T07:09:41+00:00 does not match metadata end 2025-06-06T07:09:41.998047+00:00 updating metatdata value to 2025-06-06T07:09:41+00:00
2026-01-29T14:03:57.960665-0800 | WARNING | mth5.timeseries.run_ts | validate_metadata | line: 1065 | end time of dataset 2025-06-06T14:59:41+00:00 does not match metadata end 2025-06-06T14:59:41.968750+00:00 updating metatdata value to 2025-06-06T14:59:41+00:00
2026-01-29T14:03:58.344012-0800 | WARNING | mth5.timeseries.scipy_filters | resample_poly | line: 699 | New sample rate is not an even number of original sample rate. The ratio is 4095.9999991232844.  Use the new dimensions with caution.
2026-01-29T14:03:58.409488-0800 | WARNING | mth5.timeseries.run_ts | validate_metadata | line: 1065 | end time of dataset 2025-06-06T15:09:41+00:00 does not match metadata end 2025-06-06T15:09:41.998047+00:00 updating metatdata value to 2025-06-06T15:09:41+00:00
2026-01-29T14:03:58.565473-0800 | WARNING | mth5.timeseries.scipy_filters | resample_poly | line: 699 | New sample rate is not an even number of original sample rate. The ratio is 255.99999998352212.  Use the new dimensions with caution.
2026-01-29T14:03:58.637503-0800 | WARNING | mth5.timeseries.run_ts | validate_metadata | line: 1065 | end time of dataset 2025-06-06T16:14:41+00:00 does not match metadata end 2025-06-06T16:14:41.996094+00:00 updating metatdata value to 2025-06-06T16:14:41+00:00
2026-01-29T14:03:58.747740-0800 | WARNING | mth5.timeseries.run_ts | validate_metadata | line: 1065 | end time of dataset 2025-06-06T16:14:41+00:00 does not match metadata end 2025-06-05T22:59:41.968750+00:00 updating metatdata value to 2025-06-06T16:14:41+00:00
2026-01-29T14:03:59.066567-0800 | WARNING | mth5.groups.run | from_runts | line: 1068 | Channel run.id sr256_0001 !=  group run.id sr1_0001. Setting to ch.run_metadata.id to sr1_0001
2026-01-29T14:03:59.289347-0800 | WARNING | mth5.groups.run | from_runts | line: 1068 | Channel run.id sr256_0001 !=  group run.id sr1_0001. Setting to ch.run_metadata.id to sr1_0001
2026-01-29T14:03:59.553190-0800 | WARNING | mth5.groups.run | from_runts | line: 1068 | Channel run.id sr256_0001 !=  group run.id sr1_0001. Setting to ch.run_metadata.id to sr1_0001
2026-01-29T14:04:00.047784-0800 | WARNING | mth5.groups.run | from_runts | line: 1068 | Channel run.id sr256_0001 !=  group run.id sr1_0001. Setting to ch.run_metadata.id to sr1_0001
2026-01-29T14:04:00.292807-0800 | WARNING | mth5.groups.run | from_runts | line: 1068 | Channel run.id sr256_0001 !=  group run.id sr1_0001. Setting to ch.run_metadata.id to sr1_0001
2026-01-29T14:04:01.497985-0800 | INFO | mth5.mth5 | close_mth5 | line: 899 | Flushing and closing c:\Users\jpeacock\OneDrive - DOI\MTData\CM2025\mth5\cm230.h5

In [7]:
run_list

[RunTS Summary:
 	Survey:      cm2025
 	Station:     cm205
 	Run:         sr1_0001
 	Start:       2025-06-06T23:09:58+00:00
 	End:         2025-06-07T18:34:42+00:00
 	Sample Rate: 1.0
 	Components:  ['ex', 'ey', 'hx', 'hy', 'hz'],
 RunTS Summary:
 	Survey:      cm2025
 	Station:     cm205
 	Run:         sr256_0002
 	Start:       2025-06-06T23:44:58+00:00
 	End:         2025-06-07T06:59:41.968750+00:00
 	Sample Rate: 256.0
 	Components:  ['ex', 'ey', 'hx', 'hy', 'hz'],
 RunTS Summary:
 	Survey:      cm2025
 	Station:     cm205
 	Run:         sr4096_0003
 	Start:       2025-06-07T06:59:58+00:00
 	End:         2025-06-07T07:09:41.998047+00:00
 	Sample Rate: 4096.0
 	Components:  ['ex', 'ey', 'hx', 'hy', 'hz'],
 RunTS Summary:
 	Survey:      cm2025
 	Station:     cm205
 	Run:         sr256_0004
 	Start:       2025-06-07T07:09:58+00:00
 	End:         2025-06-07T14:59:41.968750+00:00
 	Sample Rate: 256.0
 	Components:  ['ex', 'ey', 'hx', 'hy', 'hz'],
 RunTS Summary:
 	Survey:      cm2025
 	Station:     cm205
 	Run:         sr4096_0005
 	Start:       2025-06-07T14:59:58+00:00
 	End:         2025-06-07T15:09:41.998047+00:00
 	Sample Rate: 4096.0
 	Components:  ['ex', 'ey', 'hx', 'hy', 'hz'],
 RunTS Summary:
 	Survey:      cm2025
 	Station:     cm205
 	Run:         sr256_0006
 	Start:       2025-06-07T15:09:58+00:00
 	End:         2025-06-07T18:34:42+00:00
 	Sample Rate: 256.0
 	Components:  ['ex', 'ey', 'hx', 'hy', 'hz']]

In [5]:
rs.sort_values("start")

,channel_scale_factors,duration,end,has_data,input_channels,mth5_path,n_samples,output_channels,run,sample_rate,start,station,survey,run_hdf5_reference,station_hdf5_reference
0,"{'ex': 1.0, 'ey': 1.0, 'hx': 1.0, 'hy': 1.0, '...",69884.000000,2025-06-07 18:34:42+00:00,True,"[hx, hy]",c:/Users/jpeacock/OneDrive - DOI/MTData/CM2025...,69885,"[ex, ey, hz]",sr1_0001,1.0,2025-06-06 23:09:58+00:00,cm205,cm2025,<HDF5 object reference>,<HDF5 object reference>
1,"{'ex': 1.0, 'ey': 1.0, 'hx': 1.0, 'hy': 1.0, '...",26083.968750,2025-06-07 06:59:41.968750+00:00,True,"[hx, hy]",c:/Users/jpeacock/OneDrive - DOI/MTData/CM2025...,6677497,"[ex, ey, hz]",sr256_0002,256.0,2025-06-06 23:44:58+00:00,cm205,cm2025,<HDF5 object reference>,<HDF5 object reference>
4,"{'ex': 1.0, 'ey': 1.0, 'hx': 1.0, 'hy': 1.0, '...",583.998047,2025-06-07 07:09:41.998047+00:00,True,"[hx, hy]",c:/Users/jpeacock/OneDrive - DOI/MTData/CM2025...,2392057,"[ex, ey, hz]",sr4096_0003,4096.0,2025-06-07 06:59:58+00:00,cm205,cm2025,<HDF5 object reference>,<HDF5 object reference>
2,"{'ex': 1.0, 'ey': 1.0, 'hx': 1.0, 'hy': 1.0, '...",28183.968750,2025-06-07 14:59:41.968750+00:00,True,"[hx, hy]",c:/Users/jpeacock/OneDrive - DOI/MTData/CM2025...,7215097,"[ex, ey, hz]",sr256_0004,256.0,2025-06-07 07:09:58+00:00,cm205,cm2025,<HDF5 object reference>,<HDF5 object reference>
5,"{'ex': 1.0, 'ey': 1.0, 'hx': 1.0, 'hy': 1.0, '...",583.994141,2025-06-07 15:09:41.994141+00:00,True,"[hx, hy]",c:/Users/jpeacock/OneDrive - DOI/MTData/CM2025...,2392057,"[ex, ey, hz]",sr4096_0005,4096.0,2025-06-07 14:59:58+00:00,cm205,cm2025,<HDF5 object reference>,<HDF5 object reference>
3,"{'ex': 1.0, 'ey': 1.0, 'hx': 1.0, 'hy': 1.0, '...",12284.000000,2025-06-07 18:34:42+00:00,True,"[hx, hy]",c:/Users/jpeacock/OneDrive - DOI/MTData/CM2025...,3144705,"[ex, ey, hz]",sr256_0006,256.0,2025-06-07 15:09:58+00:00,cm205,cm2025,<HDF5 object reference>,<HDF5 object reference>